# Generated by Django 5.1.6 on 2025-03-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0005_comentario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='avg_calificacion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comentario',
            name='number_calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
