# Generated by Django 5.1.6 on 2025-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0006_comentario_avg_calificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='avg_calificacion',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='number_calificacion',
        ),
        migrations.AddField(
            model_name='edificacion',
            name='avg_calificacion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='edificacion',
            name='number_calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
